stages:
  - build
  - release
  - deploy
build-job:
  stage: build
  image: git.wirduzen.zone:5050/kunden/wirduzen-digital-gmbh-10005/clockify-browserextension:latest
  before_script:
    - echo GE_JOB_ID=$CI_JOB_ID >> build-job.env
  script:
    - whoami
    - npm install
    - npm run compile.prod.chrome
    - npm run compile.prod.firefox
    - zip -r chrome.zip chrome
    - zip -r firefox.zip firefox
  artifacts:
    paths:
      - firefox.zip
      - chrome.zip
    reports:
      dotenv: build-job.env
  only:
    - tags
release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Running release"
  needs:
    - job: build-job
      artifacts: true
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Download für die Browser Extensions'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Chrome'
          url: 'https://git.wirduzen.zone/kunden/wirduzen-digital-gmbh-10005/clockify-browserextension/-/jobs/${GE_JOB_ID}/artifacts/raw/chrome.zip?job=build-job'
        - name: 'Firefox'
          url: 'https://git.wirduzen.zone/kunden/wirduzen-digital-gmbh-10005/clockify-browserextension/-/jobs/${GE_JOB_ID}/artifacts/raw/firefox.zip?job=build-job'
  only:
    - tags
deploy-job:
  stage: deploy
  image: ubuntu:20.04
  needs:
    - job: build-job
      artifacts: true
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -P 222 chrome.zip wirduzm@dedivirt1815.your-server.de:~/public_html/clockify.wirduzen.dev/
    - scp -P 222 firefox.zip wirduzm@dedivirt1815.your-server.de:~/public_html/clockify.wirduzen.dev/
    - echo "$CI_COMMIT_TAG" > wdu-version.txt
    - scp -P 222 wdu-version.txt wirduzm@dedivirt1815.your-server.de:~/public_html/clockify.wirduzen.dev/
  only:
    - tags
